---
- hosts: admin
  remote_user: root

  tasks:
  - name: Get Charm++
    get_url:
      url: http://charm.cs.illinois.edu/distrib/charm-6.9.0.tar.gz
      dest: /tmp/charm-6.9.0.tar.gz
  - name: Open that archive
    unarchive:
      src: /tmp/charm-6.9.0.tar.gz
      dest: /opt/
  - name: Build Charm++
    shell: ./build AMPI mpi-linux-x86_64 mpicxx --with-production
    environment:
      MPI_HOME: /usr/lib64/mpich-3.2
      LD_LIBRARY_PATH: "/usr/lib64/mpich-3.2/lib:{{ ansible_env.LD_LIBRARY_PATH | default('') }}"
      PATH: /opt/rh/devtoolset-7/root/bin:/usr/lib64/mpich-3.2/bin:{{ ansible_env.PATH | default('') }}
    args:
      chdir: /opt/charm-6.9.0/
      creates: /tmp/charm-6.9.0/bin

- hosts: admin
  remote_user: root

  tasks:
  - name: Package Charm++
    archive:
      path: /opt/charm-6.9.0
      dest: /tmp/charm-6.9.0-local-dist.tgz

- hosts: students
  remote_user: root

  tasks:
  - name: Install Charm++
    unarchive:
      src: /tmp/charm-6.9.0-local-dist.tgz
      dest: /opt/
