---
- hosts: admin
  remote_user: root

  tasks:
  - name: Get Charm++
    get_url:
      url: http://charm.cs.illinois.edu/distrib/charm-6.9.0.tar.gz
      dest: /tmp/charm-6.9.0.tar.gz
  - name: Open that archive
    unarchive:
      src: /tmp/charm-6.9.0.tar.gz
      dest: /tmp/
  - name: Build Charm++
    shell: PATH=/usr/lib64/mpich-3.2/bin:${PATH} LD_LIBRARY_PATH=/usr/lib64/mpich-3.2/lib:${LD_LIBRARY_PATH} MPI_HOME=/usr/lib64/mpich-3.2 ./build AMPI mpi-linux-x86_64   mpicxx   --with-production
    args:
      chdir: /tmp/charm-6.9.0/
      creates: /tmp/charm-6.9.0/bin
  - name: Install Charm++
    shell: make DESTDIR=/opt/charm-6.9.0 install
    args:
      chdir: /tmp/charm-6.9.0/tmp
      creates: /opt/charm-6.9.0/bin

- hosts: admin
  remote_user: root

  tasks:
  - name: Package charm++
    archive:
      path: /tmp/charm-6.9.0
      dest: /tmp/charm-6.9.0-local-dist.tgz

- hosts: students
  remote_user: root

  tasks:
  - name: Install HPCToolkit
    unarchive:
      src: /tmp/charm-6.9.0-local-dist.tgz
      dest: /opt/
