---
- hosts: students
  remote_user: root

  tasks:
#  - name: Distribute HPCToolkit externals packages
#    copy:
#      src: /tmp/hpctoolkit-local-dist.tgz
#      dest: /tmp/hpctoolkit-local-dist.tgz
#
  - name: Install HPCToolkit externals
    unarchive:
      src: /tmp/hpctoolkit-local-dist.tgz
      dest: /opt/
