---
- hosts: admin
  remote_user: root
  vars:
    - gbench_version: "1.6.1"

  tasks:
  - name: Create gbench build directory
    file:
      path: /tmp/gbench/build
      state: directory
      mode: 700
  - name: Get Google Benchmark
    get_url:
      url: https://github.com/google/benchmark/archive/refs/tags/v{{ gbench_version }}.tar.gz
      dest: /tmp/gbench/v{{ gbench_version }}.tar.gz
  - name: Open that archive
    unarchive:
      src: /tmp/gbench/v{{ gbench_version }}.tar.gz
      dest: /tmp/gbench/
  - name: Prepare to build
    shell: cmake -DCMAKE_BUILD_TYPE=RELEASE -DBENCHMARK_ENABLE_GTEST_TESTS=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr ../benchmark-{{ gbench_version }}
    environment:
      PATH: /opt/rh/devtoolset-7/root/bin:{{ ansible_env.PATH | default('') }}
    args:
      chdir: /tmp/gbench/build
      creates: /tmp/gbench/build/Makefile
  - name: Build google benchark
    make:
      chdir: /tmp/gbench/build
      target: all
  - name: Package gbench
    archive:
      path: /tmp/gbench/build
      dest: /tmp/gbench/build.tgz
  - name: Install gbench
    make:
      chdir: /tmp/gbench/build
      target: install

- hosts: students
  remote_user: root
  vars:
    - gbench_version: "1.6.1"

  tasks:
  - name: Create gbench build directory
    file:
      path: /tmp/gbench/
      state: directory
      mode: 700
  - name: Unarchive Google Benchmark
    unarchive:
      src: /tmp/gbench/build.tgz
      dest: /tmp/gbench
  - name: Need source too
    unarchive:
        src: /tmp/gbench/v{{ gbench_version }}.tar.gz
        dest: /tmp/gbench
  - name: Install googletest
    make:
      chdir: /tmp/gbench/build
      target: install
