---
- hosts: all
  remote_user: root

  tasks:
  - name: Get libmonitor for HPCToolkit
    git:
        repo: https://github.com/HPCToolkit/libmonitor.git
        dest: /tmp/libmonitor
  - name: Configure libmonitor
      shell: bash ./configure --prefix=/opt/hpctoolkit
      args:
        chdir: /tmp/libmonitor
        creates: /tmp/libmonitor/Makefile
  - name: Compile and install libmonitor
      make:
        chdir: /tmp/libmonitor
        target: install
