---
- hosts: all
  remote_user: root

  tasks:
  - name: Get HPCToolkit
    git:
        repo: https://github.com/HPCToolkit/hpctoolkit
        dest: /tmp/hpctoolkit
  - name: Configure HPCToolkit
      shell: MPICC=mpicc MPIF77=mpif77 ./configure --with-externals=/opt/hpctoolkit/externals --with-bzip=/usr --with-papi=/usr
      args:
        chdir: /tmp/hpctoolkit
        creates: /tmp/hpctoolkit/Makefile
  - name: Compile and install HPCToolkit
      make:
        chdir: /tmp/hpctoolkit
        target: install
